import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import data from "./data/data.json";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { aboutMeData, pages } = data;
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header data={{ name: aboutMeData.name, pages }} />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
